#theme: jekyll-theme-slate
remote_theme: pages-themes/slate
title: "Zero-Effort HL2DM Config"
description: "A drop-in collection of essential performance tweaks, bug fixes, and UI improvements for Half-Life 2: Deathmatch"
show_downloads: false

plugins:
  - jekyll-remote-theme

github:
  zip_url: "https://github.com/Xeogin/Zero-Effort-HL2DM-Config/releases/latest/download/Zero-Effort-Pack.zip"
