include: ["README.md"]
#theme: jekyll-theme-slate
remote_theme: pages-themes/slate
title: "Zero-Effort HL2DM Config"
show_downloads: false

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

github:
  is_project_page: true
  zip_url: "https://github.com/Xeogin/Zero-Effort-HL2DM-Config/releases/latest/download/Zero-Effort-Pack.zip"
